

-- python -m pip install snowflake-cli-labs
-- snow --help


USE ROLE ACCOUNTADMIN;

-- Roles
SET MY_USER = CURRENT_USER();
CREATE ROLE HOL_ROLE;
-- GRANT ROLE HOL_ROLE TO ROLE SYSADMIN;
GRANT ROLE HOL_ROLE TO USER IDENTIFIER($MY_USER);

GRANT USAGE ON WAREHOUSE COMPUTE_XS TO ROLE HOL_ROLE;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE HOL_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE HOL_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_ROLE;

-- Databases
CREATE OR REPLACE DATABASE HOL_DB;
GRANT OWNERSHIP ON DATABASE HOL_DB TO ROLE HOL_ROLE;

SHOW DATABASES;

USE DATABASE HOL_DB;
CREATE SCHEMA SP_TEST;

USE ROLE HOL_ROLE;
USE WAREHOUSE COMPUTE_XS;
USE DATABASE HOL_DB;

USE SCHEMA SP_TEST;


CALL HOL_DB.SP_TEST.HELLO_WORLD_SP();

-- SELECT CURRENT_USER();